### ISSUE TITLE
Haml and Html integration

### ISSUE THREAD

**Issue by iDuuck** [jhendley25/generator-dyno#11]
Sometimes I just want to write vanilla HTML. So,  what about the integration of normal HTML?

**Comment by jhendley25** [comment]
Yeah I think we can add the choice of HTML, but I don't really want to offer the HAML choice. Jade is more node-like and fits in better with Browserify.

**Comment by iDuuck** [comment]
Okay, working on including the choice of pure HTML.

**Comment by iDuuck** [comment]
added html support, but forgot to add issue number in commit: https://github.com/jhendley25/generator-dyno/commit/637a5ba83e7a088c73c24e8b32e0e0e598b5d097
