### ISSUE TITLE
new logo

### ISSUE THREAD

**Issue by iDuuck** [jhendley25/generator-dyno#13]
hey i have done a new logo mockup
what do you think about it?

![](https://s3.amazonaws.com/f.cl.ly/items/1q1v0O0e2s3l01043K1r/Artboard%201.png)

**Comment by jhendley25** [comment]
That's awesome! Put it in the readme, and maybe in the generated index.html.

I've been meaning to redo the readme. Do you think the readme needs all the information about Yeoman?

**Comment by iDuuck** [comment]
No, I also wanted to create a new one. So, if you do so, just remove the yeoman stuff (perhaps include a link to make sure the user knows, that this is depending on Yeoman).

**Comment by jhendley25** [comment]
Ok I added the logo: 260d085a35caafd53799d35b720087876df2613a
