### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by iDuuck** [jhendley25/generator-dyno#15]
I will work on this later if there is no one that creates a faster update.

**Comment by jhendley25** [comment]
Ok. I'm covered up in work right now, so I won't be able to do much for the next couple of weeks.  Thanks for your contributions.

**Comment by iDuuck** [comment]
@jhendley25 Would be great to get push access to npmjs.org.

**Comment by jhendley25** [comment]
I'll just handle the push access to npm for now. I've noticed a couple bugs coming from PRs and commits. No big deal, but I like to test the generator well before publishing.

**Comment by iDuuck** [comment]
Fixed on https://github.com/jhendley25/generator-dyno/commit/4b7729c871f5059a7897a6ae8b867525e73592ee

*To follow up with this: I am going to rewrite the index.js of the generator. After this I am writing extensive tests to cover every aspect of the generator, so we could integrate the generator into travis-ci.org and just test it on every push. So you will get an email for every failed test.*
