### ISSUE TITLE
Broken logo on npm.

### ISSUE THREAD

**Issue by jhendley25** [jhendley25/generator-dyno#17]
![screen shot 2015-03-26 at 2 37 50 pm](https://cloud.githubusercontent.com/assets/5239363/6854210/404afeaa-d3c6-11e4-8c46-4de63bcab1f3.png)

**Comment by iDuuck** [comment]
fixed on https://github.com/jhendley25/generator-dyno/commit/91dde92509342dc2be0b908ef5600b1b18188a87
