### ISSUE TITLE
Ability to skip opening of browser (browser-sync module)

### ISSUE THREAD

**Issue by iDuuck** [jhendley25/generator-dyno#21]

**Comment by eko24** [comment]
Hi @iDuuck !  
I found this flag for browser-sync config called [open](http://www.browsersync.io/docs/options/#option-open)  
So I simply added it to the `serve` task where `browserSync` calls:  
```
browserSync({
    notify: false,
    port: 9000,
    open: true,
    server: {
      baseDir: ['.tmp', 'app'],
      routes: {
        '/bower_components': 'bower_components'
      }
    }
  });
```
But unfortunately this doesn't worked out, so I have no idea how to make it :disappointed:

**Comment by iDuuck** [comment]
Hey Erik, when I am at work today, I will add this. It's easy as hell. But
thanks for your effort.
