### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by iDuuck** [jhendley25/generator-dyno#23]
since i am deep into work at the moment, please can someone update the dependencies, so they are up-to-date again? perhaps @jhendley25?

**Comment by jhendley25** [comment]
sure thing

**Comment by mentorkadriu** [comment]
I just  updated dependencies :)

**Comment by jhendley25** [comment]
looks like we both did @mentorkadriu. I just pushed the changes.

**Comment by iDuuck** [comment]
@jhendley25 You had the wrong version of `gulp-load-plugins`. Fixed this now!

**Comment by mentorkadriu** [comment]
Yeah! But all fixed now.
