### ISSUE TITLE
Jade not compiles to HTML

### ISSUE THREAD

**Issue by akhalizev** [jhendley25/generator-dyno#35]
Jade compiles to html only when I run "gulp templates" command.
If I am running "gulp" or "gulp serve" jade not compiles.

**Comment by iDuuck** [comment]
Is there an error message? Also, which version are you using?

**Comment by akhalizev** [comment]
I don't see any error messages. My yeoman version is 1.4.6. Dyno was installed today.

**Comment by jhendley25** [comment]
@akhalizev thanks for the issue. That bug should be fixed now.
