### ISSUE TITLE
Browserify Modules installed with Bower cannot be found.

### ISSUE THREAD

**Issue by iDuuck** [jhendley25/generator-dyno#4]
Hello,
when using the generator and installing things over bower it's not possible to `require` them in my JS files.

```
[13:15:27] Plumber found unhandled error:
 Error in plugin 'gulp-browserify'
module "jquery" not found from "/path/to/project/src/scripts/fake_5089a368.js"
```

What's the matter with this?

**Comment by jhendley25** [comment]
Are you requiring the full path? For example "require('bower_components/jquery/jquery.js')"?

require("jquery") will only work for packages installed in the node_modules folder.

**Comment by iDuuck** [comment]
Because of a straight deadline I used static files for now. If I am experiencing the issue again or if i have time to check, I will get back to this issue.

Thanks!
