### ISSUE TITLE
Make bower optional

### ISSUE THREAD

**Issue by MiniGod** [jhendley25/generator-dyno#6]
I know I won't use bower for my project, so I'll just remove the bower related files for now.

Could you do to bower as you did to coffescript; make it optional?

**Comment by jhendley25** [comment]
Sure thing. I'll get to this soon. PRs are always welcome too. :)

**Comment by iDuuck** [comment]
I have done a new commit for this issue.

**Comment by jhendley25** [comment]
Thanks @iDuuck, open a pr for this and I'll merge it in.
