### ISSUE TITLE
Optional .sass or .scss files

### ISSUE THREAD

**Issue by iDuuck** [jhendley25/generator-dyno#9]
What about offering optional switching from SCSS to Sass?

**Comment by jhendley25** [comment]
That would be nice. I think it's possible to just support both without having to choose. Possibly by watching both .sass and .scss here: https://github.com/jhendley25/generator-dyno/blob/master/app/templates/_gulpfileJavascript.js#L18

**Comment by iDuuck** [comment]
Yeah, but the first scaffolding of the files.
